name: Automated API tests using Postman CLI

on:
  push:
  schedule:
    - cron: '*/5 * * * *' # This schedules the job to run every 5 minutes

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "30277426-7d4ff7fe-683e-4632-a94f-d6de5f0fffb9" --reporters cli,json --reporter-json-export report.json

      - name: List files for debugging
        run: ls -la

      - name: Send Email with POSTMAN Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Postman API Test Report
          to: orji.motopayng@gmail.com
          from: ndubuisiaso@gmail.com
          body: Attached is the Postman API test report."
          attachments: report.json