name: Automated API tests using Newman CLI

on:
  push:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Newman CLI and the enhanced HTML reporter
      - name: Install Newman CLI and Enhanced HTML Reporter
        run: |
          npm install -g newman newman-reporter-html-reporter

      # Run the Postman collection with Newman and generate an enhanced HTML report
      - name: Run API tests
        id: run_tests
        run: |
          newman run "Platzi Fake Store API.postman_collection.json" --reporters cli,html-reporter --reporter-html-reporter-export report.html || exit 1

      # List files for debugging
      - name: List files for debugging
        run: ls -la

      # Optional: Process the report.html file to check for errors or issues
      - name: Process HTML Report
        run: |
          # Example of processing the report.html
          echo "Enhanced HTML report generated successfully."

      # Send email with enhanced HTML report
      - name: Send Email with Postman Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Postman API Test Report
          to: orji.motopayng@gmail.com
          from: ndubuisiaso@gmail.com
          body: |
            Attached is the enhanced Postman API test report in HTML format.
          attachments: report.html
