name: Automated API tests using Postman CLI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 mins
  workflow_dispatch:


jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "30277426-7d4ff7fe-683e-4632-a94f-d6de5f0fffb9"

      - name: Send Email with POSTMAN Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Shop APi Test Report
          to: orji.motopayng@gmail.com
          from: ndubuisiaso@gmail.com
          body: "Please find attached API scheduled test report."
          content_type: text/html
          attachments: postman-report/index.html